name: apply

on:
  push:
    branches: master

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      #### git checkout
      - uses: actions/checkout@v3

      - name: create comment
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'apply comment dayo'
            })