name: concurrency-workflow

on:
  pull_request:
    branches: master
    types:
      - opened
      - synchronize
      - closed

concurrency: test-cc

jobs:
  concurrency_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sleep 60
