name: dryrun

on:
  pull_request:
    branches: master
    types:
      - opened
      - synchronize

jobs:
  dryrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: pipefaile test
        run: |
          ./scripts/echo-test | tee comment
          STATUS="$?"
          exit $STATUS

      #### post result
      - name: post result as comment
        uses: actions/github-script@v6
        with:
          script: |
            const { promises: fs } = require('fs')
            let content = await fs.readFile('comment', 'utf8')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: content
            })
