name: dryrun

on:
  pull_request:
    branches: master
    types:
      - opened
      - synchronize

jobs:
  dryrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: dryrun test
        id: dryrun_test
        continue-on-error: true
        shell: bash -o pipefail {0}
        run: |
          ./scripts/echo-test 2>&1 | tee comment
          STATUS="$?"
          exit $STATUS

      #### post result
      - name: post result as comment
        if: ${{ steps.dryrun_test.outcome == 'success' }} || ${{ steps.dryrun_test.outcome == 'failure' }}
        uses: actions/github-script@v6
        with:
          script: |
            const { promises: fs } = require('fs')
            let content = await fs.readFile('comment', 'utf8')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: content
            })

      - name: dryrun result
        if: ${{ steps.dryrun_test.outcome == 'failure' }}
        # When the dryrun test step fails, set this job to failed status
        run: |
          exit 1
