name: Test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set merge-base
      run: |
        hash=$(git merge-base HEAD master)
        echo "::set-output name=MergeBase::${hash}"
      id: merge-base

    - name: test get merge-base
      run: echo 'The MergeBase is' ${{ steps.merge-base.outputs.MergeBase }}

