name: Test
on:
  pull_request:
    branches:
    - master
    paths:
    - 'sql/*.sql'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: get skeema
      run: |
        mkdir -p /tmp/skeema-ci
        cd /tmp/skeema-ci
        curl -s -L https://github.com/skeema/skeema/releases/download/v1.4.5/skeema_1.4.5_linux_amd64.tar.gz > skeema.tar.gz
        tar xzf skeema.tar.gz skeema

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.base.sha }}

    - name: checkout and docker run
      run: |
        docker run \
          -d \
          --name mysql-skeema \
          -v ${{ github.workspace }}/sql/:/docker-entrypoint-initdb.d/ \
          -e MYSQL_DATABASE=test \
          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes \
          -e TZ=Asia/Tokyo \
          -p 3306:3306 \
          mysql:5.7
        sleep 15

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: skeema diff
      run: |
        set -o pipefail
        cd ${{ github.workspace }}/sql
        /tmp/skeema-ci/skeema push skeema-diff-ci --allow-unsafe --ddl-wrapper='echo "\n-- skeema:ddl:begin\n"{DDL}";\n-- skeema:ddl:end"' | sed -n '/^-- skeema:ddl:begin/,/^-- skeema:ddl:end/p' | sed -e '/^-- skeema:/d' | tee /tmp/skeema-ci/skeema-diff.sql

    - name: create comment
      run: |
        echo "_Automatically generated schema diff statements_" >> /tmp/comment.txt
        echo "Update Date: $(date --rfc-3339=seconds)" >> /tmp/comment.txt
        echo "Compare: https://github.com/${{ github.repository }}/compare/${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}" >> /tmp/comment.txt
        echo "\`\`\`sql" >> /tmp/comment.txt
        cat /tmp/skeema-ci/skeema-diff.sql >> /tmp/comment.txt
        echo "\`\`\`" >> /tmp/comment.txt

    - uses: marocchino/sticky-pull-request-comment@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        header: DDL
        path: /tmp/comment.txt
