name: Test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: set merge-base
      run: |
        hash=$(git merge-base HEAD master)
        echo "::set-output name=MergeBase::${hash}"
      id: merge-base

    - name: checkout and docker run
      run: |
        git checkout ${{ steps.merge-base.outputs.MergeBase }}
        docker run \
          -d \
          --name mysql-skeema \
          -v $(pwd)/sql/:/docker-entrypoint-initdb.d/ \
          -e MYSQL_DATABASE=test \
          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes \
          -e TZ=Asia/Tokyo \
          -p 3306:3306 \
          mysql:5.7

    - name: mysql show tables
      run: mysql -u root -h 127.0.0.1 test -e 'show tables'

